name: 'amazon_reviews'
version: '1.0.0'
config-version: 2

profile: 'amazon_reviews'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  amazon_reviews:
    staging:
      +schema: staging
      +materialized: view
    marts:
      core:
        +schema: core
        +materialized: table
      business:
        +schema: business
        +materialized: table

seeds:
  +schema: seed_data
  +materialized: table