name: 'amazon_reviews'
version: '1.0.0'
config-version: 2

profile: 'amazon_reviews'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Add this variable to control elementary data monitoring
vars:
  elementary:
    full_refresh_data_monitoring: true # Set to true for full refresh or false for incremental

models:
  amazon_reviews:
    staging:
      +schema: staging
      +materialized: view
    marts:
      core:
        +schema: core
        +materialized: table
      business:
        +schema: business
        +materialized: table

seeds:
  +schema: seed_data
  +materialized: table

# Add hooks for metadata logging
on-run-end:
  - "{{ log_dbt_metadata(results) }}" # Call our custom macro after each run